// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: unifi.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetAnomaliesClient is the client API for GetAnomalies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetAnomaliesClient interface {
	GetClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
}

type getAnomaliesClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAnomaliesClient(cc grpc.ClientConnInterface) GetAnomaliesClient {
	return &getAnomaliesClient{cc}
}

func (c *getAnomaliesClient) GetClient(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, "/api.unifi_v1.GetAnomalies/GetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAnomaliesServer is the server API for GetAnomalies service.
// All implementations must embed UnimplementedGetAnomaliesServer
// for forward compatibility
type GetAnomaliesServer interface {
	GetClient(context.Context, *ClientRequest) (*ClientResponse, error)
	mustEmbedUnimplementedGetAnomaliesServer()
}

// UnimplementedGetAnomaliesServer must be embedded to have forward compatible implementations.
type UnimplementedGetAnomaliesServer struct {
}

func (UnimplementedGetAnomaliesServer) GetClient(context.Context, *ClientRequest) (*ClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedGetAnomaliesServer) mustEmbedUnimplementedGetAnomaliesServer() {}

// UnsafeGetAnomaliesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetAnomaliesServer will
// result in compilation errors.
type UnsafeGetAnomaliesServer interface {
	mustEmbedUnimplementedGetAnomaliesServer()
}

func RegisterGetAnomaliesServer(s grpc.ServiceRegistrar, srv GetAnomaliesServer) {
	s.RegisterService(&GetAnomalies_ServiceDesc, srv)
}

func _GetAnomalies_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAnomaliesServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.unifi_v1.GetAnomalies/GetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAnomaliesServer).GetClient(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetAnomalies_ServiceDesc is the grpc.ServiceDesc for GetAnomalies service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetAnomalies_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.unifi_v1.GetAnomalies",
	HandlerType: (*GetAnomaliesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClient",
			Handler:    _GetAnomalies_GetClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unifi.proto",
}
